/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('animals').del()
  await knex('animals').insert([
    {
      id: 1,
      type: "bird",
      name: "Charlie",
      age: 2,
      gender: "male",
      weight: "0.7 lbs",
      breed: "African Grey Parrot",
      alt: "Intelligent African Grey Parrot",
      image: "/birds/African-Grey-Parrot.jpg",
      description: "Charlie is a captivating African Grey parrot with stunning gray feathers and a vibrant red tail. This intelligent and charismatic bird is eagerly searching for a forever home. With a talent for mimicking human speech, Charlie's melodic voice can bring laughter and joy to any household. He enjoys perching on shoulders or stands, observing his surroundings with a curious eye. Charlie's diet includes fresh fruits like apples and bananas, along with vegetables like carrots and broccoli. His favorite treats are almonds and walnuts. Charlie loves puzzle toys and colorful chew toys that keep his sharp mind and beak occupied. Give Charlie a loving home and enjoy his playful companionship."
    },
    {
      id: 2,
      type: "bird",
      name: "Lola",
      age: 1,
      gender: "female",
      weight: "0.4 lbs",
      breed: "Alexandrine Parakeet",
      alt: "Colorful Alexandrine Parakeet",
      image: "/birds/Alexandrine-Parakeet.jpg",
      description: "Meet Lola, a charming Alexandrine Parakeet eagerly seeking a loving forever home. Lola is a vibrant avian companion with stunning emerald plumage and a playful disposition. This delightful parakeet relishes in social interactions, eagerly chirping and mimicking human speech with her enchanting melodic voice. Lola enjoys exploring her surroundings, adeptly climbing and swinging on her favorite toys. When it comes to meals, Lola's palate delights in a variety of fresh fruits, vegetables, and nutrient-rich pellets, ensuring she maintains a balanced diet. Ready to grace your home with her joyful presence, Lola promises to bring endless entertainment and companionship to her lucky adopter."
    },
    {
      id: 3,
      type: "bird",
      name: "Rio",
      age: 3,
      gender: "male",
      weight: "1.0 lbs",
      breed: "Amazon Parrot",
      alt: "Talkative Amazon Parrot",
      image: "/birds/Amazon-Parrot.jpg",
      description: "Introducing Rio, an enchanting Amazon Parrot eagerly awaiting a forever home. With vibrant feathers displaying a kaleidoscope of colors, Rio is a true avian beauty. This charismatic parrot thrives on human interaction, engaging in delightful conversations and showcasing a remarkable ability to mimic sounds and voices. Rio's playful nature shines through as he delights in solving puzzles and exploring his surroundings with his inquisitive beak. When it comes to dining, Rio has a penchant for fresh fruits, leafy greens, and a specialized pellet diet that provides him with optimal nutrition. Adopting Rio means welcoming a lifelong feathered companion filled with intelligence, charm, and boundless affection."
    },
    {
      id: 4,
      type: "bird",
      name: "Sunny",
      age: 2,
      gender: "female",
      weight: "1.5 lbs",
      breed: "Blue-and-Gold Macaw",
      alt: "Vibrant Blue-And-Gold Macaw",
      image: "/birds/Blue-And-Gold-Macaw.jpg",
      description: "Meet Sunny, a captivating Blue and Gold Macaw eagerly seeking a loving forever home. With majestic cobalt blue feathers and vibrant golden accents, Sunny is a true spectacle of beauty. This charismatic macaw thrives on social interactions, delighting in human companionship and displaying an impressive repertoire of vocalizations, including mimicking speech and singing melodiously. Sunny's energetic nature is complemented by a love for exploration and play, with a particular fondness for toys that challenge his intelligence. When it comes to mealtimes, Sunny enjoys a varied diet consisting of fresh fruits, vegetables, nuts, and high-quality pellets, ensuring his health and well-being. Adopting Sunny means inviting a magnificent, affectionate, and highly intelligent feathered friend into your life."
    },
    {
      id: 5,
      type: "bird",
      name: "Pippin",
      age: 1,
      gender: "male",
      weight: "0.6 lbs",
      breed: "Blue Crowned Conure",
      alt: "Cheerful Blue Crowned Conure",
      image: "/birds/Blue-Crowned-Conure.jpg",
      description: "Introducing Pippin, a delightful Blue Crowned Conure eagerly awaiting a forever home. With vibrant shades of green and a striking blue crown atop his head, Pippin is a visually stunning avian companion. Known for their playful and affectionate nature, Pippin thrives on social interaction and craves human companionship. This intelligent conure loves engaging in interactive games and showing off his acrobatic skills. When it comes to meals, Pippin enjoys a diverse diet that includes fresh fruits, vegetables, seeds, and a specialized pellet mix, ensuring he receives a balanced and nutritious feast. Adopting Pippin means inviting a charming, joyful, and engaging feathered friend into your home."
    },
    {
      id: 6,
      type: "bird",
      name: "Milo",
      age: 2,
      gender: "male",
      weight: "0.9 lbs",
      breed: "Blue Headed Pionus",
      alt: "Stunning Blue Headed Pionus",
      image: "/birds/Blue-Headed-Pionus.jpg",
      description: "Meet Milo, an enchanting Blue Headed Pionus eagerly seeking a loving forever home. With a beautiful blend of deep blues and vibrant greens on his head and body, Milo is a true avian gem. Known for their calm and gentle nature, Milo is an ideal companion for those seeking a tranquil and harmonious household. Milo loves to explore his surroundings, displaying an inquisitive nature, and enjoys perching on his favorite branches while observing his surroundings. When it comes to meals, Milo savors a balanced diet consisting of fresh fruits, vegetables, high-quality pellets, and occasional treats like nuts and seeds. Adopting Milo means embracing a serene, intelligent, and captivating feathered companion."
    },
    {
      id: 7,
      type: "bird",
      name: "Sky",
      age: 1,
      gender: "female",
      weight: "0.3 lbs",
      breed: "Budgie Parakeet",
      alt: "Playful Budgie Parakeet",
      image: "/birds/Budgie-Parakeet.jpg",
      description: "Introducing Sky, a charming Budgie Parakeet eagerly seeking a loving forever home. With a captivating blend of vibrant blues, greens, and yellows, Sky is a true avian beauty. Known for their playful and social nature, Sky thrives on human interaction and delights in bonding with their adopter. Sky loves to flutter around their surroundings, exploring every nook and cranny with their curious beak. When it comes to mealtimes, Sky enjoys a varied diet consisting of fresh fruits, vegetables, high-quality seeds, and nutrient-rich pellets, ensuring they receive a well-rounded nutritional intake. Adopting Sky means inviting a joyful, interactive, and affectionate feathered friend into your life."
    },
    {
      id: 8,
      type: "bird",
      name: "Tango",
      age: 2,
      gender: "male",
      weight: "0.8 lbs",
      breed: "Caique",
      alt: "Energetic Caique bird",
      image: "/birds/Caique.jpg",
      description: "Introducing Tango, a spirited Caique parrot eagerly seeking a loving forever home. With their striking combination of vibrant colors including orange, green, and white, Tango is a visual delight. Known for their playful and mischievous nature, Tango is a ball of energy, always ready for an adventure. Tango loves to explore their surroundings, utilizing their acrobatic skills and entertaining antics to bring joy to those around them. When it comes to meals, Tango enjoys a diverse diet that includes fresh fruits, vegetables, high-quality pellets, and occasional treats like nuts and seeds. Adopting Tango means embracing a lively, entertaining, and charismatic feathered companion into your home."
    },
    {
      id: 9,
      type: "bird",
      name: "Sunny",
      age: 1,
      gender: "female",
      weight: "0.4 lbs",
      breed: "Canary",
      alt: "Melodious Canary",
      image: "/birds/Canary.jpg",
      description: "Meet Sunny, a melodious Canary eagerly seeking a loving forever home. With his vibrant yellow plumage and melodic voice, Sunny is a true avian delight. Known for their enchanting songs, Sunny brings a symphony of joy to any household. Sunny loves to perch on his swing or branch, serenading his surroundings with his melodious tunes. When it comes to meals, Sunny enjoys a balanced diet that includes a variety of seeds, fresh greens, and occasional fruits. Adopting Sunny means inviting a feathered companion with a captivating voice and a sunny disposition into your life, adding a touch of harmony and cheerfulness to your home."
    },
    {
      id: 10,
      type: "bird",
      name: "Coco",
      age: 2,
      gender: "male",
      weight: "0.5 lbs",
      breed: "Cockatiel",
      alt: "Friendly Cockatiel",
      image: "/birds/Cockatiel.jpg",
      description: "Introducing Coco, an adorable Cockatiel eagerly awaiting a loving forever home. With his striking crest and soft gray feathers, Coco is a true avian charmer. Known for their friendly and sociable nature, Coco thrives on human companionship and enjoys spending time interacting with his adopter. Coco loves to explore his surroundings, hopping and flying from perch to perch, while entertaining with his playful antics. When it comes to meals, Coco enjoys a varied diet consisting of high-quality pellets, fresh fruits, vegetables, and the occasional treat of seeds or nuts. Adopting Coco means embracing a delightful, affectionate, and entertaining feathered friend into your life."
    },
    {
      id: 11,
      type: "bird",
      name: "Max",
      age: 3,
      gender: "male",
      weight: "1.2 lbs",
      breed: "Cockatoo",
      alt: "Gorgeous Cockatoo",
      image: "/birds/Cockatoo.jpg",
      description: "Meet Max, an enchanting Cockatoo eagerly seeking a loving forever home. With his magnificent crest and snowy white plumage, Max is a stunning avian companion. Known for their intelligence and affectionate nature, Max forms deep bonds with his human companions, seeking constant interaction and cuddles. Max loves to showcase his impressive vocal abilities, mimicking sounds and engaging in delightful conversations. When it comes to meals, Max enjoys a varied diet consisting of fresh fruits, vegetables, high-quality pellets, and occasional treats like nuts or seeds. Adopting Max means inviting a loving, intelligent, and entertaining feathered friend into your home, ready to bring joy and companionship for a lifetime."
    },
    {
      id: 12,
      type: "bird",
      name: "Kiwi",
      age: 2,
      gender: "female",
      weight: "0.9 lbs",
      breed: "Conure",
      alt: "Colorful Conure",
      image: "/birds/Conure.jpg",
      description: "Introducing Kiwi, a vibrant Conure eagerly awaiting a loving forever home. With his stunning combination of green feathers and captivating personality, Kiwi is a true avian gem. Known for their playful and outgoing nature, Kiwi thrives on social interaction and craves human companionship. Kiwi loves to explore his surroundings, eagerly climbing, and investigating every nook and cranny. With his charming and inquisitive nature, Kiwi enjoys learning new tricks and engaging in interactive playtime. When it comes to meals, Kiwi delights in a varied diet of fresh fruits, vegetables, high-quality pellets, and the occasional treat of seeds or nuts. Adopting Kiwi means inviting a lively, affectionate, and entertaining feathered friend into your life."
    },
    {
      id: 13,
      type: "bird",
      name: "Ruby",
      age: 1,
      gender: "female",
      weight: "0.3 lbs",
      breed: "Crimson Rosella",
      alt: "Beautiful Crimson Rosella",
      image: "/birds/Crimson-Rosella.jpg",
      description: "Introducing Ruby, a magnificent Crimson Rosella eagerly seeking a loving forever home. With her vibrant red plumage, deep blue cheeks, and striking tail feathers, Ruby is a true avian masterpiece. Known for their intelligence and playful nature, Ruby loves engaging in interactive games and solving puzzles. Ruby's melodic calls and mimicry abilities add a delightful charm to her presence. When it comes to meals, Ruby enjoys a diverse diet that includes a mix of fresh fruits, vegetables, seeds, and high-quality pellets. Adopting Ruby means inviting a striking, intelligent, and captivating feathered companion into your home, ready to enchant you with her beauty and joyful antics."
    },
    {
      id: 14,
      type: "bird",
      name: "Dusty",
      age: 2,
      gender: "male",
      weight: "0.2 lbs",
      breed: "Diamond Dove",
      alt: "Graceful Diamond Dove",
      image: "/birds/Diamond-Dove.jpg",
      description: "Meet Dusty, a delightful Diamond Dove eagerly seeking a loving forever home. With his soft, dove-gray plumage and sparkling red eyes, Dusty is a true avian beauty. Known for their gentle and peaceful nature, Dusty brings a sense of calm and serenity to any household. Dusty enjoys perching on his favorite branches, observing his surroundings with a keen eye. When it comes to meals, Dusty appreciates a balanced diet consisting of fresh seeds, grains, and a variety of leafy greens. Adopting Dusty means welcoming a tranquil and captivating feathered companion into your home, adding a touch of grace and elegance to your life."
    },
    {
      id: 15,
      type: "bird",
      name: "Finn",
      age: 1,
      gender: "male",
      weight: "0.1 lbs",
      breed: "Finch",
      alt: "Charming Finch",
      image: "/birds/Finch.jpg",
      description: "Meet Finn, a delightful Finch eagerly awaiting a loving forever home. With his small and colorful frame, Finn brings a touch of vibrancy to any aviary. Known for their lively and social nature, Finn enjoys the company of fellow finches and human companions alike. Finn loves to flutter and fly around, showcasing his agile movements and chirping cheerfully. When it comes to meals, Finn thrives on a diet consisting of high-quality finch seed mix, fresh greens, and the occasional treat of fruits or millet sprays. Adopting Finn means embracing a charming, sociable, and melodious feathered companion into your life."
    },
    {
      id: 16,
      type: "bird",
      name: "Mocchi",
      age: 2,
      gender: "female",
      weight: "0.3 lbs",
      breed: "Lory",
      alt: "Colorful Lory bird",
      image: "/birds/Lory.jpg",
      description: "Introducing Mocchi, a captivating Lory eagerly seeking a loving forever home. With their vibrant plumage and expressive eyes, Mocchi is a true avian gem. Known for their playful and affectionate nature, Mocchi thrives on social interaction and craves human companionship. Mocchi loves to engage in interactive playtime, exploring toys and showing off their acrobatic skills. When it comes to meals, Mocchi enjoys a specialized nectar-based diet supplemented with fresh fruits and occasional treats. Adopting Mocchi means inviting a charismatic, intelligent, and entertaining feathered friend into your life, ready to bring a burst of color and joy to your home."
    },
    {
      id: 17,
      type: "bird",
      name: "Ozzy",
      age: 3,
      gender: "male",
      weight: "1.8 lbs",
      breed: "Macaw",
      alt: "Magnificent Macaw",
      image: "/birds/Macaw.jpg",
      description: "Meet Ozzy, a magnificent Macaw eagerly awaiting a loving forever home. With his vibrant feathers and impressive wingspan, Ozzy is a true avian marvel. Known for their intelligence and strong bonds, Ozzy forms deep connections with their human companions, craving affection and interaction. Ozzy loves to showcase his vocal abilities, belting out an array of sounds and mimicry with remarkable clarity. When it comes to meals, Ozzy enjoys a varied diet that includes a mix of fresh fruits, vegetables, nuts, and high-quality pellets. Adopting Ozzy means inviting a majestic, intelligent, and captivating feathered companion into your life, ready to add brilliance and companionship to your home."
    },
    {
      id: 18,
      type: "bird",
      name: "Piper",
      age: 2,
      gender: "female",
      weight: "0.3 lbs",
      breed: "Song Canary",
      alt: "Melodious Song Canary",
      image: "/birds/Song-Canary.jpg",
      description: "Introducing Piper, a charming Song Canary eagerly seeking a loving forever home. With his melodious voice and vibrant feathers, Piper is a true avian treasure. Known for their captivating songs, Piper fills the air with enchanting melodies, bringing joy and tranquility to any space. Piper enjoys perching on his swing, showcasing his vocal prowess, and expressing his love for music. When it comes to meals, Piper thrives on a balanced diet consisting of high-quality canary seed mix, fresh greens, and the occasional treat of soft fruits. Adopting Piper means inviting a harmonious, delightful, and tuneful feathered friend into your life."
    },
    {
      id: 19,
      type: "bird",
      name: "Oliver",
      age: 1,
      gender: "male",
      weight: "0.7 lbs",
      breed: "Vasa Parrot",
      alt: "Colorful Vasa Parrot",
      image: "/birds/Vasa-Parrot.jpg",
      description: "Meet Oliver, a captivating Vasa Parrot eagerly seeking a loving forever home. With his sleek black plumage and striking beak, Oliver is a true avian beauty. Known for their intelligent and inquisitive nature, Oliver thrives on mental stimulation and enjoys solving puzzles and playing with interactive toys. Oliver also has a knack for mimicry, delighting in imitating various sounds and voices. When it comes to meals, Oliver enjoys a varied diet that includes high-quality pellets, fresh fruits, vegetables, and the occasional treat of nuts or seeds. Adopting Oliver means inviting a fascinating, clever, and charismatic feathered companion into your home."
    },
    {
      id: 20,
      type: "bird",
      name: "Peach",
      age: 1,
      gender: "female",
      weight: "0.9 lbs",
      breed: "Sun Conure",
      alt: "Colorful Sun Conure",
      image: "/birds/Sun-Conure.jpg",
      description: "Introducing Peach, a radiant Sun Conure eagerly seeking a loving forever home. With their vibrant plumage blending shades of orange, yellow, and green, Peach is a true avian gem. Known for their playful and affectionate nature, Peach thrives on social interaction and craves human companionship. Peach loves engaging in interactive playtime, showing off their acrobatic skills and charming antics. When it comes to meals, Peach enjoys a diverse diet consisting of fresh fruits, vegetables, high-quality pellets, and occasional treats like nuts or seeds. Adopting Peach means inviting a lively, spirited, and loving feathered friend into your life, ready to brighten every moment with their vibrant personality."
    },
    {
      id: 21,
      type: "cat",
      name: "Luna",
      age: 2,
      gender: "female",
      weight: "9.8 lbs",
      breed: "Maine Coon",
      alt: "A majestic Maine Coon cat",
      image: "/cats/Maine-Coon.jpg",
      description: "Meet Luna, the majestic Maine Coon. With her large size and tufted ears, Luna is a gentle giant with a loving disposition. She enjoys exploring her surroundings, scaling heights, and playing with interactive toys. Luna has a hearty appetite and savors high-quality cat food with a preference for wet food that satisfies her Maine Coon size."
    },
    {
      id: 22,
      type: "cat",
      name: "Oliver",
      age: 4,
      gender: "male",
      weight: "10.5 lbs",
      breed: "British Shorthair",
      alt: "A charming British Shorthair cat",
      image: "/cats/British-Shorthair.jpg",
      description: "Introducing Oliver, the charming British Shorthair. With his round face and plush coat, Oliver is a delightful companion. He loves lounging in cozy spots, observing the world from a distance, and engaging in gentle play. Oliver appreciates a balanced diet with a mix of dry and wet food, as well as occasional treats to satisfy his refined taste."
    },
    {
      id: 23,
      type: "cat",
      name: "Bella",
      age: 1,
      gender: "female",
      weight: "10.1 lbs",
      breed: "Bengal",
      alt: "A stunning Bengal cat",
      image: "/cats/Bengal.jpg",
      description: "Say hello to Bella, the exotic Bengal. With her distinctive coat featuring beautiful spots or marbled patterns, Bella is an energetic and curious feline. She enjoys an active lifestyle, engaging in interactive play sessions, and having access to stimulating toys. Bella thrives on a diet rich in high-quality protein, and her Bengal heritage makes her particularly fond of a raw or grain-free diet."
    },
    {
      id: 24,
      type: "cat",
      name: "Chloe",
      age: 2,
      gender: "female",
      weight: "10.2 lbs",
      breed: "Persian",
      alt: "A fluffy Persian cat",
      image: "/cats/Persian.jpg",
      description: "Meet Chloe, the regal Persian beauty. Known for her luxurious coat and sweet temperament, Chloe prefers a calm and serene environment, where she can relax on soft pillows and enjoy gentle brushing sessions. She enjoys a diet consisting of high-quality, specially formulated food that helps maintain her Persian coat's health and beauty."
    },
    {
      id: 25,
      type: "cat",
      name: "Max",
      age: 3,
      gender: "male",
      weight: "9.9 lbs",
      breed: "Scottish Fold",
      alt: "An adorable Scottish Fold cat",
      image: "/cats/Scottish-Fold.jpg",
      description: "Introducing Max, the adorable Scottish Fold. With his folded ears and playful antics, Max charms everyone he meets. He loves interactive toys that challenge his clever mind and enjoys a cozy spot by the window to watch the world go by. Max's diet consists of a balanced mix of wet and dry food, providing him with the necessary nutrients for his active lifestyle."
    },
    {
      id: 26,
      type: "cat",
      name: "Daisy",
      age: 1,
      gender: "female",
      weight: "10.2 lbs",
      breed: "Sphynx",
      alt: "A unique Sphynx cat",
      image: "/cats/Sphynx.jpg",
      description: "Say hello to Daisy, the unique Sphynx. With her warm and affectionate nature, Daisy is a social butterfly who thrives on human companionship. She loves being the center of attention and enjoys a diet of high-quality cat food that supports her unique skin and coat needs, with a focus on keeping her skin moisturized and maintaining her overall health."
    },


    {
      id: 27,
      type: "cat",
      name: "Rocky",
      age: 4,
      gender: "male",
      weight: "9.9 lbs",
      breed: "Siberian",
      alt: "A beautiful Siberian cat",
      image: "/cats/Siberian.jpg",
      description: "Meet Rocky, the adventurous Siberian. With his playful and agile nature, Rocky is always ready for an exciting adventure. He enjoys climbing, exploring his surroundings, and engaging in interactive playtime with puzzle toys. Rocky has a well-rounded diet that includes a mix of high-quality dry and wet food, providing him with the energy he needs to satisfy his active lifestyle."
    },
    {
      id: 28,
      type: "cat",
      name: "Zoe",
      age: 3,
      gender: "female",
      weight: "10.2 lbs",
      breed: "Russian Blue",
      alt: "An elegant Russian Blue cat",
      image: "/cats/Russian-Blue.jpg",
      description: "Introducing Zoe, the elegant Russian Blue. With her graceful demeanor and intelligence, Zoe exudes charm wherever she goes. She enjoys a calm and serene environment, where she can observe her surroundings with a keen eye. Zoe appreciates a diet that includes high-quality protein sources and plenty of fresh water, which keeps her coat shiny and her body in optimal condition."
    },

    {
      id: 29,
      type: "cat",
      name: "Lola",
      age: 2,
      gender: "female",
      weight: "10.2 lbs",
      breed: "Siamese",
      alt: "A playful Siamese cat",
      image: "/cats/Siamese.jpg",
      description: "Meet Lola, the elegant Siamese. With her striking blue eyes and sleek coat, Lola is a true beauty. She enjoys being the center of attention and engaging in interactive play sessions. Lola has a refined palate and prefers a diet that includes high-quality, protein-rich food to keep her in top shape."
    },
    {
      id: 30,
      type: "cat",
      name: "Misty",
      age: 2,
      gender: "female",
      weight: "9.7 lbs",
      breed: "Abyssinian",
      alt: "An elegant Abyssinian cat",
      image: "/cats/Abyssinian.jpg",
      description: "Introducing Misty, the playful Abyssinian. With her ticked coat and vibrant personality, Misty is a joy to be around. She loves chasing toys, exploring her surroundings, and playing hide-and-seek. Misty thrives on a diet that includes a mix of wet and dry food, providing her with the necessary nutrients for her active lifestyle."
    },
    {
      id: 31,
      type: "cat",
      name: "Rocky",
      age: 3,
      gender: "male",
      weight: "9.8 lbs",
      breed: "Birman",
      alt: "A beautiful Birman cat",
      image: "/cats/Birman.jpg",
      description: "Say hello to Rocky, the charming Birman. With his striking blue eyes and silky coat, Rocky is a true charmer. He enjoys a peaceful and harmonious environment, where he can relax and cuddle up with his favorite humans. Rocky's diet consists of high-quality cat food that supports his overall well-being."
    },
    {
      id: 32,
      type: "cat",
      name: "Lulu",
      age: 1,
      gender: "female",
      weight: "9.6 lbs",
      breed: "Chartreux",
      alt: "A charming Chartreux cat",
      image: "/cats/Chartreux.jpg",
      description: "Meet Lulu, the gentle Chartreux. With her robust build and stunning blue-gray coat, Lulu is a lovely companion. She enjoys a calm and serene atmosphere, where she can spend her time relaxing and observing her surroundings. Lulu appreciates a diet that includes high-quality, balanced cat food that keeps her healthy and content."
    },
    {
      id: 33,
      type: "cat",
      name: "Charlie",
      age: 4,
      gender: "male",
      weight: "9.5 lbs",
      breed: "Cornish Rex",
      alt: "A playful Cornish Rex cat",
      image: "/cats/Cornish-Rex.jpg",
      description: "Introducing Charlie, the playful Cornish Rex. With his curly coat and mischievous personality, Charlie is always ready for an adventure. He loves interactive toys, climbing to high places, and entertaining his human companions with his acrobatic skills. Charlie's diet includes high-quality food that supports his high energy levels."
    },
    {
      id: 34,
      type: "cat",
      name: "Lucy",
      age: 2,
      gender: "female",
      weight: "9.7 lbs",
      breed: "Devon Rex",
      alt: "An adorable Devon Rex cat",
      image: "/cats/Devon-Rex.jpg",
      description: "Say hello to Lucy, the charming Devon Rex. With her wavy coat and affectionate nature, Lucy is a delightful companion. She loves curling up in warm laps, playing with feather toys, and spending quality time with her humans. Lucy's diet consists of nutritious, high-quality cat food that keeps her coat glossy and her energy levels up."
    },
    {
      id: 35,
      type: "cat",
      name: "Leo",
      age: 3,
      gender: "male",
      weight: "9.8 lbs",
      breed: "Egyptian Mau",
      alt: "A sleek Egyptian Mau cat",
      image: "/cats/Egyptian-Mau.jpg",
      description: "Meet Leo, the regal Egyptian Mau. With his striking spotted coat and athletic build, Leo is a true sight to behold. He enjoys interactive play, chasing toys, and showing off his impressive agility. Leo thrives on a diet rich in high-quality protein, supporting his active lifestyle and overall health."
    },
    {
      id: 36,
      type: "cat",
      name: "Milo",
      age: 1,
      gender: "male",
      weight: "9.6 lbs",
      breed: "Havana Brown",
      alt: "A unique Havana Brown cat",
      image: "/cats/Havana-Brown.jpg",
      description: "Havana Brown: Introducing Milo, the charming Havana Brown. With his rich chocolate-colored coat and affectionate nature, Milo is a loving companion. He enjoys interactive play sessions, cozying up in laps, and engaging in gentle grooming. Milo's diet includes a balanced mix of high-quality cat food, providing him with the necessary nutrients for a healthy and happy life."
    },
    {
      id: 37,
      type: "cat",
      name: "Lola",
      age: 4,
      gender: "female",
      weight: "9.5 lbs",
      breed: "Japanese Bobtail",
      alt: "An elegant Japanese Bobtail cat",
      image: "/cats/Japanese-Bobtail.jpg",
      description: "Meet Lola, the playful Japanese Bobtail. With her unique bobbed tail and lively personality, Lola is full of charm. She enjoys interactive playtime and has a knack for learning tricks. Lola's diet consists of high-quality cat food that provides her with the energy she needs for her adventures."
    },
    {
      id: 38,
      type: "cat",
      name: "Oliver",
      age: 2,
      gender: "male",
      weight: "9.7 lbs",
      breed: "Korat",
      alt: "A stunning Korat cat",
      image: "/cats/Korat.jpg",
      description: "Introducing Oliver, the elegant Korat. With his shimmering silver-blue coat and captivating green eyes, Oliver is a true beauty. He enjoys a peaceful and calm environment, where he can relax and observe his surroundings. Oliver's diet includes high-quality, nutritious food to support his overall well-being."
    },
    {
      id: 39,
      type: "cat",
      name: "Lily",
      age: 1,
      gender: "female",
      weight: "9.8 lbs",
      breed: "Manx",
      alt: "A tailless Manx cat",
      image: "/cats/Manx.jpg",
      description: "Say hello to Lily, the spirited Manx. With her expressive eyes and distinctive tailless body, Lily is a unique companion. She loves to play, especially with toys that challenge her agility and intelligence. Lily thrives on a diet rich in high-quality protein, which keeps her active and healthy."
    },
    {
      id: 40,
      type: "cat",
      name: "Oscar",
      age: 3,
      gender: "male",
      weight: "9.6 lbs",
      breed: "Norwegian Forest",
      alt: "A majestic Norwegian Forest cat",
      image: "/cats/Norwegian-Forest.jpg",
      description: "Meet Oscar, the majestic Norwegian Forest cat. With his long, flowing coat and sturdy build, Oscar is a true adventurer. He enjoys exploring the outdoors and climbing trees. Oscar's diet includes high-quality cat food that supports his active lifestyle and maintains his magnificent coat."
    },
    {
      id: 41,
      type: "cat",
      name: "Chloe",
      age: 2,
      gender: "female",
      weight: "9.5 lbs",
      breed: "Ocicat",
      alt: "A spotted Ocicat cat",
      image: "/cats/Ocicat.jpg",
      description: "Introducing Chloe, the captivating Ocicat. With her wild-spotted coat and curious nature, Chloe is always ready for an exciting escapade. She enjoys interactive play sessions and thrives on mental stimulation. Chloe's diet consists of high-quality, balanced food that provides her with the necessary nutrients for her active lifestyle."
    },
    {
      id: 42,
      type: "cat",
      name: "Max",
      age: 4,
      gender: "male",
      weight: "9.7 lbs",
      breed: "Ragamuffin",
      alt: "A fluffy Ragamuffin cat",
      image: "/cats/Ragamuffin.jpg",
      description: "Say hello to Max, the cuddly Ragamuffin. With his plush coat and affectionate personality, Max is a true sweetheart. He loves being held and enjoys lap time with his humans. Max's diet includes high-quality cat food that supports his overall well-being and keeps his luxurious fur in top condition."
    },
    {
      id: 43,
      type: "cat",
      name: "Luna",
      age: 1,
      gender: "female",
      weight: "9.8 lbs",
      breed: "Somali",
      alt: "A beautiful Somali cat",
      image: "/cats/Somali.jpg",
      description: "Meet Luna, the elegant Somali. With her beautiful long-haired coat and playful nature, Luna is a delightful companion. She loves interactive play, such as chasing toys and exploring her surroundings. Luna's diet consists of high-quality food that provides her with the necessary nutrients for her active lifestyle."
    },
    {
      id: 44,
      type: "cat",
      name: "Simba",
      age: 3,
      gender: "male",
      weight: "9.6 lbs",
      breed: "Tonkinese",
      alt: "A playful Tonkinese cat",
      image: "/cats/Tonkinese.jpg",
      description: "Introducing Simba, the charismatic Tonkinese. With his sparkling blue eyes and soft, silky coat, Simba is a true charmer. He enjoys interactive play sessions and loves spending quality time with his human family. Simba's diet includes a balanced mix of high-quality cat food, providing him with the necessary nutrition for a healthy and happy life."
    },
    {
      id: 45,
      type: "cat",
      name: "Daisy",
      age: 2,
      gender: "female",
      weight: "9.5 lbs",
      breed: "Turkish Angora",
      alt: "An elegant Turkish Angora cat",
      image: "/cats/Turkish-Angora.jpg",
      description: "Meet Daisy, the elegant Turkish Angora. With her silky, long white coat and striking blue or green eyes, Daisy is a true beauty. She is known for her playful and affectionate nature, enjoying interactive play sessions and spending time with her human companions. Daisy's diet includes high-quality cat food that provides her with the necessary nutrients for her active lifestyle."
    },
    {
      id: 46,
      type: "cat",
      name: "Jack",
      age: 4,
      gender: "male",
      weight: "9.7 lbs",
      breed: "Turkish Van",
      alt: "A charming Turkish Van cat",
      image: "/cats/Turkish-Van.jpg",
      description: "Introducing Jack, the adventurous Turkish Van. With his striking patterned coat and love for water, Jack is a fun-loving companion. He enjoys swimming, exploring outdoor spaces, and engaging in interactive play. Jack's diet consists of high-quality cat food that supports his active nature and provides him with the necessary energy for his adventures."
    },
    {
      id: 47,
      type: "cat",
      name: "Sophie",
      age: 2,
      gender: "female",
      weight: "9.8 lbs",
      breed: "American Bobtail",
      alt: "A unique American Bobtail cat",
      image: "/cats/American-Bobtail.jpg",
      description: "American Bobtail: Say hello to Sophie, the charming American Bobtail. With her bobbed tail and playful personality, Sophie is a delightful companion. She loves interactive toys and games that challenge her intelligence. Sophie's diet includes high-quality, nutritious cat food that supports her active lifestyle and overall well-being."
    },
    {
      id: 48,
      type: "cat",
      name: "Tigger",
      age: 3,
      gender: "male",
      weight: "9.6 lbs",
      breed: "American Curl",
      alt: "A curious American Curl cat",
      image: "/cats/American-Curl.jpg",
      description: "Meet Tigger, the curious American Curl. With his distinctive curled ears and friendly nature, Tigger is an endearing feline. He enjoys interactive play and is always up for exploring new places. Tigger's diet consists of high-quality cat food that provides him with the necessary nutrients for his active and curious lifestyle."
    },
    {
      id: 49,
      type: "cat",
      name: "Coco",
      age: 1,
      gender: "female",
      weight: "9.5 lbs",
      breed: "Balinese",
      alt: "An elegant Balinese cat",
      image: "/cats/Balinese.jpg",
      description: "Introducing Coco, the elegant Balinese. With her long, silky coat and graceful demeanor, Coco is a true beauty. She enjoys a calm and serene environment, where she can relax and be pampered. Coco's diet includes high-quality cat food that supports her overall well-being and keeps her coat healthy and glossy."
    },
    {
      id: 50,
      type: "cat",
      name: "Gizmo",
      age: 4,
      gender: "male",
      weight: "9.7 lbs",
      breed: "Bombay",
      alt: "A sleek Bombay cat",
      image: "/cats/Bombay.jpg",
      description: "Say hello to Gizmo, the sleek and playful Bombay. With his shiny black coat and captivating golden eyes, Gizmo is a charming companion. He loves interactive play sessions and enjoys being the center of attention. Gizmo's diet includes high-quality cat food that provides him with the necessary nutrients for his active lifestyle."
    },
    {
      id: 51,
      type: "dog",
      name: "Max",
      age: 3,
      gender: "male",
      weight: "65 lbs",
      breed: "Labrador Retriever",
      alt: "A friendly and outgoing Labrador Retriever",
      image: "/dogs/Labrador-Retriever.jpg",
      description: "Meet Max, the friendly Labrador Retriever. With his glossy coat and wagging tail, Max is a true people-pleaser. He enjoys playing fetch, going for long walks, and swimming. Max has an appetite for high-quality dog food that provides him with the necessary nutrients for his active lifestyle."
    },
    {
      id: 52,
      type: "dog",
      name: "Bella",
      age: 2,
      gender: "female",
      weight: "12 lbs",
      breed: "Poodle",
      alt: "An elegant and intelligent Poodle",
      image: "/dogs/Poodle.jpg",
      description: "Meet Bella, the elegant Poodle. With her curly, hypoallergenic coat and intelligent demeanor, Bella is a sophisticated companion. She excels in obedience training, enjoys mental stimulation, and loves participating in dog sports. Bella's diet consists of high-quality dog food that keeps her coat healthy and her mind sharp."
    },
    {
      id: 53,
      type: "dog",
      name: "Luna",
      age: 1,
      gender: "female",
      weight: "50 lbs",
      breed: "Bulldog",
      alt: "A gentle and affectionate Bulldog",
      image: "/dogs/Bulldog.jpg",
      description: "Introducing Luna, the adorable Bulldog. With her wrinkled face and lovable personality, Luna is a delightful companion. She enjoys leisurely walks, snuggling on the couch, and engaging in gentle playtime. Luna's diet consists of a balanced mix of high-quality dog food that keeps her healthy and content."
    },
    {
      id: 54,
      type: "dog",
      name: "Lucy",
      age: 3,
      gender: "female",
      weight: "25 lbs",
      breed: "French Bulldog",
      alt: "A small and affectionate French Bulldog",
      image: "/dogs/French-Bulldog.jpg",
      description: "Say hello to Lucy, the playful French Bulldog. With her bat-like ears and affectionate nature, Lucy is a joy to be around. She loves interactive play, short walks, and spending quality time with her human family. Lucy's diet includes high-quality dog food that supports her overall well-being and keeps her in good shape."
    },
    {
      id: 55,
      type: "dog",
      name: "Rocky",
      age: 5,
      gender: "male",
      weight: "80 lbs",
      breed: "German Shepherd",
      alt: "A loyal and courageous German Shepherd",
      image: "/dogs/German-Shepherd.jpg",
      description: "Meet Rocky, the loyal German Shepherd. With his noble appearance and intelligence, Rocky is a wonderful companion. He enjoys obedience training, engaging in mentally stimulating activities, and going for long hikes. Rocky's diet consists of high-quality dog food that provides him with the necessary energy for his active lifestyle."
    },
    {
      id: 56,
      type: "dog",
      name: "Bella",
      age: 4,
      gender: "female",
      weight: "10 lbs",
      breed: "Havanese",
      alt: "A small and friendly Havanese",
      image: "/dogs/Havanese.jpg",
      description: "Introducing Bella, the charming Havanese. With her silky coat and friendly demeanor, Bella is a delightful companion. She loves being around people, going for leisurely walks, and participating in fun agility exercises. Bella's diet includes high-quality dog food that keeps her coat shiny and her body healthy."
    },
    {
      id: 57,
      type: "dog",
      name: "Charlie",
      age: 4,
      gender: "male",
      weight: "22 lbs",
      breed: "Beagle",
      alt: "A friendly and scent-driven Beagle",
      image: "/dogs/Beagle.jpg",
      description: "Say hello to Charlie, the spirited Beagle. With his floppy ears and inquisitive nature, Charlie is always ready for an adventure. He enjoys exploring scents, engaging in interactive games, and going on long walks. Charlie's diet includes high-quality dog food that provides him with the necessary nutrition for his active lifestyle."
    },
    {
      id: 58,
      type: "dog",
      name: "Lucy",
      age: 2,
      gender: "female",
      weight: "65 lbs",
      breed: "Boxer",
      alt: "An energetic and playful Boxer",
      image: "/dogs/Boxer.jpg",
      description: "Meet Lucy, the energetic Boxer. With her muscular build and playful personality, Lucy is a bundle of joy. She enjoys vigorous play sessions, going for runs, and participating in training activities. Lucy's diet consists of high-quality dog food that supports her active lifestyle and provides her with the necessary nutrients."
    },
    {
      id: 59,
      type: "dog",
      name: "Rocky",
      age: 3,
      gender: "male",
      weight: "15 lbs",
      breed: "Jack Russell Terrier",
      alt: "An energetic and fearless Jack Russell Terrier",
      image: "/dogs/Jack-Russell-Terrier.jpg",
      description: "Introducing Rocky, the spirited Jack Russell Terrier. With his compact size and boundless energy, Rocky is always on the go. He loves engaging in mentally stimulating activities, playing fetch, and going on adventurous hikes. Rocky's diet includes high-quality dog food that provides him with the necessary energy to keep up with his active nature."
    },
    {
      id: 60,
      type: "dog",
      name: "Cooper",
      age: 6,
      gender: "male",
      weight: "55 lbs",
      breed: "Dalmatian",
      alt: "A unique and energetic Dalmatian",
      image: "/dogs/Dalmatian.jpg",
      description: "Introducing Cooper, the lively Dalmatian. With his distinctive spots and boundless energy, Cooper is always ready for action. He loves going for runs, participating in agility training, and playing interactive games. Cooper's diet includes high-quality dog food that provides him with the necessary energy for his active lifestyle."
    },
    {
      id: 61,
      type: "dog",
      name: "Daisy",
      age: 3,
      gender: "female",
      weight: "70 lbs",
      breed: "Golden Retriever",
      alt: "A friendly and loyal Golden Retriever",
      image: "/dogs/Golden-Retriever.jpg",
      description: "Say hello to Daisy, the friendly Golden Retriever. With her beautiful golden coat and gentle nature, Daisy is a beloved family companion. She enjoys playing fetch, going for long walks, and swimming. Daisy's diet consists of high-quality dog food that supports her overall well-being and maintains her healthy coat."
    },
    {
      id: 62,
      type: "dog",
      name: "Max",
      age: 4,
      gender: "male",
      weight: "60 lbs",
      breed: "Siberian Husky",
      alt: "An athletic and striking Siberian Husky",
      image: "/dogs/Siberian-Husky.jpg",
      description: "Meet Max, the adventurous Siberian Husky. With his striking blue or multicolored eyes and thick coat, Max is a true explorer. He loves outdoor activities, such as sledding, hiking, and running. Max's diet includes high-quality dog food that provides him with the necessary nutrients for his active and robust nature."
    },
    {
      id: 63,
      type: "dog",
      name: "Bella",
      age: 2,
      gender: "female",
      weight: "90 lbs",
      breed: "Husky",
      alt: "A beautiful and energetic Husky",
      image: "/dogs/Husky.jpg",
      description: "Introducing Bella, the playful Husky. With her stunning appearance and friendly personality, Bella is a delightful companion. She enjoys interactive play sessions, going for long walks, and participating in dog sports like agility or obedience. Bella's diet consists of high-quality dog food that supports her active lifestyle and keeps her coat in top condition."
    },
    {
      id: 64,
      type: "dog",
      name: "Lola",
      age: 2,
      gender: "female",
      weight: "15 lbs",
      breed: "Chihuahua",
      alt: "A small and alert Chihuahua",
      image: "/dogs/Chihuahua.jpg",
      description: "Say hello to Lola, the tiny Chihuahua with a big personality. With her expressive eyes and spunky nature, Lola is a true charmer. She enjoys cuddling, short walks, and playing with toys suitable for her size. Lola's diet includes high-quality dog food that provides her with the necessary nutrients for her petite frame."
    },
    {
      id: 65,
      type: "dog",
      name: "Rocky",
      age: 5,
      gender: "male",
      weight: "90 lbs",
      breed: "Rottweiler",
      alt: "A strong and protective Rottweiler",
      image: "/dogs/Rottweiler.jpg",
      description: "Meet Rocky, the loyal Rottweiler. With his strong build and protective nature, Rocky is a devoted family companion. He enjoys obedience training, engaging in physically challenging activities, and spending quality time with his loved ones. Rocky's diet consists of high-quality dog food that supports his active lifestyle and keeps him strong."
    },
    {
      id: 66,
      type: "dog",
      name: "Buddy",
      age: 2,
      gender: "male",
      weight: "55 lbs",
      breed: "Border Collie",
      alt: "A highly intelligent and energetic Border Collie",
      image: "/dogs/Border-Collie.jpg",
      description: "Introducing Buddy, the intelligent Border Collie. With his keen herding instincts and quick learning abilities, Buddy is a remarkable working dog. He excels in obedience training, enjoys mental stimulation, and thrives when given tasks to complete. Buddy's diet includes high-quality dog food that provides him with the necessary nutrients for his active and agile nature."
    },
    {
      id: 67,
      type: "dog",
      name: "Lily",
      age: 4,
      gender: "female",
      weight: "18 lbs",
      breed: "Shih Tzu",
      alt: "A cute and affectionate Shih Tzu",
      image: "/dogs/Shih-Tzu.jpg",
      description: "Meet Lily, the adorable Shih Tzu. With her luxurious, long coat and gentle disposition, Lily is a lovable companion. She enjoys leisurely walks, snuggling on laps, and spending quality time with her family. Lily's diet consists of high-quality dog food that keeps her healthy and nourished."
    },
    {
      id: 68,
      type: "dog",
      name: "Lux",
      age: 4,
      gender: "male",
      weight: "35 lbs",
      breed: "Shiba Inu",
      alt: "A spirited and independent Shiba Inu",
      image: "/dogs/Shiba-Inu.jpg",
      description: "Introducing Lux, the spirited Shiba Inu. With his fox-like appearance and independent nature, Lux is a captivating companion. He enjoys daily walks, mentally stimulating games, and participating in activities that challenge his intelligence. Lux's diet includes high-quality dog food that supports his active lifestyle and maintains his well-being."
    },
    {
      id: 69,
      type: "dog",
      name: "Rocky",
      age: 5,
      gender: "male",
      weight: "50 lbs",
      breed: "Basset Hound",
      alt: "A short-legged and friendly Basset Hound",
      image: "/dogs/Basset-Hound.jpg",
      description: "Say hello to Rocky, the charming Basset Hound. With his droopy ears and friendly demeanor, Rocky is a true sweetheart. He enjoys leisurely walks, sniffing around in the outdoors, and spending quality time with his loved ones. Rocky's diet consists of high-quality dog food that provides him with the necessary nutrients for his laid-back lifestyle."
    },
    {
      id: 70,
      type: "dog",
      name: "Charlie",
      age: 3,
      gender: "male",
      weight: "75 lbs",
      breed: "Doberman Pinscher",
      alt: "A loyal and alert Doberman Pinscher",
      image: "/dogs/Doberman-Pinscher.jpg",
      description: "Meet Charlie, the loyal Doberman Pinscher. With his sleek coat and confident personality, Charlie is a devoted companion. He thrives on mental and physical stimulation, enjoying activities such as obedience training, running, and playing interactive games. Charlie's diet includes high-quality dog food that supports his active nature and overall well-being."
    },
    {
      id: 71,
      type: "dog",
      name: "Lucy",
      age: 6,
      gender: "female",
      weight: "75 lbs",
      breed: "Bernese Mountain Dog",
      alt: "A large and gentle Bernese Mountain Dog",
      image: "/dogs/Bernese-Mountain-Dog.jpg",
      description: "Introducing Lucy, the gentle Bernese Mountain Dog. With her striking tri-color coat and calm demeanor, Lucy is a beloved family pet. She enjoys leisurely walks, spending time outdoors, and being around her loved ones. Lucy's diet consists of high-quality dog food that provides her with the necessary nutrition for her large and robust frame."
    },
    {
      id: 72,
      type: "dog",
      name: "Mocha",
      age: 3,
      gender: "female",
      weight: "25 lbs",
      breed: "Shetland Sheepdog",
      alt: "A fluffy cute Shetland Sheepdog",
      image: "/dogs/Shetland-Sheepdog.jpg",
      description: "Say hello to Mocha, the intelligent Shetland Sheepdog. With her luscious double coat and agile nature, Mocha is a remarkable companion. She excels in obedience training, enjoys mentally stimulating activities, and thrives on having a job to do. Mocha's diet includes high-quality dog food that supports her active and intelligent nature."
    },
    {
      id: 73,
      type: "dog",
      name: "Lola",
      age: 2,
      gender: "female",
      weight: "20 lbs",
      breed: "Corgi",
      alt: "A short-legged and affectionate Corgi",
      image: "/dogs/Corgi.jpg",
      description: "Meet Lola, the charismatic Corgi. With her short legs and happy disposition, Lola is a delightful companion. She enjoys daily walks, playing fetch, and participating in activities that challenge her agility. Lola's diet consists of high-quality dog food that provides her with the necessary nutrients for her active lifestyle."
    },
    {
      id: 74,
      type: "dog",
      name: "Cooper",
      age: 3,
      gender: "male",
      weight: "25 lbs",
      breed: "Pug",
      alt: "A wrinkled and playful Pug",
      image: "/dogs/Pug.jpg",
      description: "Introducing Cooper, the lovable Pug. With his wrinkled face and affectionate personality, Cooper is a true charmer. He enjoys being around people, going for leisurely walks, and engaging in interactive playtime. Cooper's diet includes high-quality dog food that supports his overall well-being and keeps him happy and healthy."
    },
    {
      id: 75,
      type: "dog",
      name: "Bear",
      age: 4,
      gender: "male",
      weight: "100 lbs",
      breed: "Great Dane",
      alt: "A giant and gentle Great Dane",
      image: "/dogs/Great-Dane.jpg",
      description: "Meet Bear, the majestic Great Dane. With his towering height and gentle nature, Bear is a true gentle giant. He enjoys leisurely walks, lounging around, and spending quality time with his family. Bear's diet consists of high-quality dog food that provides him with the necessary nutrition for his large size."
    },
    {
      id: 76,
      type: "dog",
      name: "Oscar",
      age: 5,
      gender: "male",
      weight: "60 lbs",
      breed: "Australian Shepherd",
      alt: "A loyal and intelligent Australian Shepherd",
      image: "/dogs/Australian-Shepherd.jpg",
      description: "Introducing Oscar, the intelligent Australian Shepherd. With his beautiful coat and energetic personality, Oscar is a remarkable companion. He excels in obedience training, enjoys agility exercises, and thrives when given mental and physical challenges. Oscar's diet includes high-quality dog food that supports his active lifestyle and provides him with the necessary nutrients."
    },
    {
      id: 77,
      type: "dog",
      name: "Bailey",
      age: 4,
      gender: "male",
      weight: "30 lbs",
      breed: "Cavalier King Charles Spaniel",
      alt: "A friendly and graceful Cavalier King Charles Spaniel",
      image: "/dogs/Cavalier-King-Charles-Spaniel.jpg",
      description: "Say hello to Bailey, the affectionate Cavalier King Charles Spaniel. With his expressive eyes and friendly demeanor, Bailey is a beloved family pet. He enjoys leisurely walks, cuddling with his loved ones, and participating in gentle playtime. Bailey's diet consists of high-quality dog food that keeps him healthy and nourished."
    },
    {
      id: 78,
      type: "dog",
      name: "Sophie",
      age: 3,
      gender: "female",
      weight: "25 lbs",
      breed: "Pomeranian",
      alt: "A fluffy and playful Pomeranian",
      image: "/dogs/Pomeranian.jpg",
      description: "Meet Sophie, the adorable Pomeranian. With her fluffy coat and lively personality, Sophie is a delightful companion. She loves attention, playing with toys, and going for short walks. Sophie's diet includes high-quality dog food that supports her overall well-being and keeps her coat healthy and shiny."
    },
    {
      id: 79,
      type: "dog",
      name: "Luna",
      age: 5,
      gender: "female",
      weight: "12 lbs",
      breed: "Dachshund",
      alt: "A long-bodied and playful Dachshund",
      image: "/dogs/Dachshund.jpg",
      description: "Introducing Luna, the spirited Dachshund. With her long body and playful nature, Luna is a bundle of energy. She enjoys daily walks, playing with toys suitable for her size, and engaging in mentally stimulating activities. Luna's diet consists of high-quality dog food that provides her with the necessary nutrients for her active lifestyle."
    },
    {
      id: 80,
      type: "dog",
      name: "Max",
      age: 2,
      gender: "male",
      weight: "55 lbs",
      breed: "Australian Cattle Dog",
      alt: "A loyal and active Australian Cattle Dog",
      image: "/dogs/Australian-Cattle-Dog.jpg",
      description: "Say hello to Max, the loyal Australian Cattle Dog. With his sturdy build and alert personality, Max is a devoted companion. He excels in obedience training, enjoys physical challenges such as hiking or agility, and thrives on having a job to do. Max's diet includes high-quality dog food that supports his active nature and overall well-being."
    },
    {
      id: 81,
      type: "rabbit",
      name: "Fluffy",
      age: 2,
      gender: "male",
      weight: "1.5 lbs",
      breed: "Lionhead",
      alt: "Adorable lionhead rabbit",
      image: "/rabbits/Lionhead.jpg",
      description: "Meet Fluffy, the adorable Lionhead rabbit. With its distinctive mane-like fur and gentle nature, Fluffy is an endearing companion. Fluffy enjoys hopping around, exploring its surroundings, and receiving gentle pets. Its diet consists of fresh hay, a variety of leafy greens, and high-quality rabbit pellets to keep it healthy and content."
    },
    {
      id: 82,
      type: "rabbit",
      name: "Coco",
      age: 1,
      gender: "female",
      weight: "0.8 lbs",
      breed: "Dutch",
      alt: "Beautiful Dutch rabbit",
      image: "/rabbits/Dutch.jpg",
      description: "Introducing Coco, the charming Dutch rabbit. With its sleek and colorful coat, Coco is a delightful addition to any home. Coco loves to hop and play, and enjoys spending time with its human family. Its diet consists of fresh hay, a mix of vegetables, and high-quality rabbit pellets to provide the essential nutrients it needs."
    },

    {
      id: 83,
      type: "rabbit",
      name: "Hazel",
      age: 2,
      gender: "female",
      weight: "1.1 lbs",
      breed: "Netherland Dwarf",
      alt: "Tiny Netherland Dwarf rabbit",
      image: "/rabbits/Netherland-Dwarf.jpg",
      description: "Say hello to Hazel, the tiny Netherland Dwarf rabbit. With its compact size and playful personality, Hazel is full of energy and curiosity. Hazel loves exploring its environment, participating in interactive playtime, and munching on fresh hay and a variety of fresh vegetables for a well-balanced diet."
    },
    {
      id: 84,
      type: "rabbit",
      name: "Oliver",
      age: 4,
      gender: "male",
      weight: "1.8 lbs",
      breed: "Flemish Giant",
      alt: "Giant Flemish rabbit",
      image: "/rabbits/Flemish-Giant.jpg",
      description: "Meet Oliver, the majestic Flemish Giant rabbit. With its impressive size and docile nature, Oliver is a gentle giant. Oliver enjoys leisurely hopping around, relaxing in comfortable spaces, and spending quality time with its human companions. Its diet includes unlimited fresh hay, a selection of leafy greens, and high-quality rabbit pellets to support its growth and health."
    },
    {
      id: 85,
      type: "rabbit",
      name: "Luna",
      age: 2,
      gender: "female",
      weight: "1.2 lbs",
      breed: "Holland Lop",
      alt: "Sweet Holland Lop rabbit",
      image: "/rabbits/Holland-Lop.jpg",
      description: "Introducing Luna, the adorable Holland Lop rabbit. With its floppy ears and sweet temperament, Luna is an absolute sweetheart. Luna enjoys cuddling, hopping around during playtime, and nibbling on fresh hay and a variety of rabbit-safe vegetables for a well-rounded diet."
    },
    {
      id: 86,
      type: "rabbit",
      name: "Max",
      age: 1,
      gender: "male",
      weight: "1.0 lbs",
      breed: "Jersey Wooly",
      alt: "Fluffy Jersey Wooly rabbit",
      image: "/rabbits/Jersey-Wooly.jpg",
      description: "Say hello to Max, the fluffy Jersey Wooly rabbit. With its wool-like fur and gentle disposition, Max is an adorable companion. Max enjoys being petted, engaging in gentle play, and munching on fresh hay and a mix of leafy greens to maintain its health and happiness."
    },

    {
      id: 87,
      type: "rabbit",
      name: "Rocky",
      age: 2,
      gender: "male",
      weight: "1.7 lbs",
      breed: "Rex",
      alt: "Velvety Rex rabbit",
      image: "/rabbits/Rex.jpg",
      description: "Meet Rocky, the velvety Rex rabbit. With its unique fur texture and friendly personality, Rocky is a charming pet. Rocky loves to explore its surroundings, participate in interactive play, and enjoys a diet of fresh hay, rabbit-safe vegetables, and high-quality rabbit pellets."
    },

    {
      id: 88,
      type: "rabbit",
      name: "Oscar",
      age: 3,
      gender: "male",
      weight: "2.0 lbs",
      breed: "English Lop",
      alt: "Floppy-eared English Lop rabbit",
      image: "/rabbits/English-Lop.jpg",
      description: "Introducing Oscar, the elegant English Lop rabbit. With its long, floppy ears and gentle nature, Oscar is a delightful addition to any home. Oscar enjoys hopping around, receiving gentle pets, and relishing a diet of fresh hay, a variety of vegetables, and high-quality rabbit pellets to keep it healthy and nourished."
    },

    {
      id: 89,
      type: "rabbit",
      name: "Charlie",
      age: 2,
      gender: "male",
      weight: "1.6 lbs",
      breed: "Dwarf Hotot",
      alt: "Cute Dwarf Hotot rabbit",
      image: "/rabbits/Dwarf-Hotot.jpg",
      description: "Say hello to Charlie, the adorable Dwarf Hotot rabbit. With its distinctive black eyeliner and compact size, Charlie is a lovable companion. Charlie enjoys exploring its environment, participating in gentle play, and feasting on fresh hay and a variety of rabbit-safe vegetables for a balanced diet."
    },
    {
      id: 90,
      type: "rabbit",
      name: "Benny",
      age: 1,
      gender: "male",
      weight: "0.9 lbs",
      breed: "Mini Rex",
      alt: "Adorable Mini Rex rabbit",
      image: "/rabbits/Mini-Rex.jpg",
      description: "Meet Benny, the charming Mini Rex rabbit. With his velvety fur and friendly personality, Benny is a delightful companion. He enjoys exploring his surroundings, playing with toys, and receiving gentle pets. Benny's diet consists of a balanced mix of fresh hay, vegetables, and specially formulated rabbit pellets."
    },
    {
      id: 91,
      type: "rabbit",
      name: "Lily",
      age: 3,
      gender: "female",
      weight: "1.3 lbs",
      breed: "Harlequin",
      alt: "Colorful Harlequin rabbit",
      image: "/rabbits/Harlequin.jpg",
      description: "Introducing Lily, the beautiful Harlequin rabbit. With her distinct coat pattern and playful nature, Lily is a joy to be around. She loves hopping around in spacious enclosures, engaging in interactive play, and nibbling on fresh greens. Lily's diet includes a variety of hay, vegetables, and high-quality rabbit pellets."
    },
    {
      id: 92,
      type: "rabbit",
      name: "Milo",
      age: 2,
      gender: "male",
      weight: "1.5 lbs",
      breed: "Angora",
      alt: "Fluffy Angora rabbit",
      image: "/rabbits/Angora.jpg",
      description: "Say hello to Milo, the fluffy Angora rabbit. With his long, luxurious wool and gentle temperament, Milo is a unique companion. He requires regular grooming to maintain his coat, and he enjoys spending time being brushed and pampered. Milo's diet consists of a balanced mix of hay, fresh vegetables, and high-fiber pellets."
    },
    {
      id: 93,
      type: "rabbit",
      name: "Sophie",
      age: 1,
      gender: "female",
      weight: "0.8 lbs",
      breed: "Mini Lop",
      alt: "Sweet Mini Lop rabbit",
      image: "/rabbits/Mini-Lop.jpg",
      description: "Meet Sophie, the adorable Mini Lop rabbit. With her floppy ears and friendly nature, Sophie is a lovable pet. She enjoys hopping around in a safe, bunny-proofed space, playing with toys, and receiving gentle attention. Sophie's diet includes fresh hay, leafy greens, and high-quality rabbit pellets."
    },
    {
      id: 94,
      type: "rabbit",
      name: "Olive",
      age: 2,
      gender: "female",
      weight: "1.1 lbs",
      breed: "American Fuzzy Lop",
      alt: "Fluffy American Fuzzy Lop rabbit",
      image: "/rabbits/American-Fuzzy-Lop.jpg",
      description: "Introducing Olive, the cuddly American Fuzzy Lop rabbit. With her soft, fuzzy coat and docile demeanor, Olive is a delightful companion. She enjoys exploring her surroundings, relaxing in cozy spots, and receiving gentle pets. Olive's diet consists of fresh hay, a variety of vegetables, and high-quality rabbit pellets."
    },
    {
      id: 95,
      type: "rabbit",
      name: "Maxwell",
      age: 4,
      gender: "male",
      weight: "1.8 lbs",
      breed: "Silver Marten",
      alt: "Sleek Silver Marten rabbit",
      image: "/rabbits/Silver-Marten.jpg",
      description: "Say hello to Maxwell, the sleek Silver Marten rabbit. With his striking coat and playful personality, Maxwell is a unique pet. He enjoys hopping around, engaging in interactive play, and having a variety of toys to keep him entertained. Maxwell's diet includes fresh hay, leafy greens, and high-fiber rabbit pellets."
    },
    {
      id: 96,
      type: "rabbit",
      name: "Daisy",
      age: 2,
      gender: "female",
      weight: "1.2 lbs",
      breed: "Lop-eared",
      alt: "Cute Lop-eared rabbit",
      image: "/rabbits/Lop-Eared.jpg",
      description: "Meet Daisy, the adorable Lop-Eared rabbit. With her droopy ears and gentle nature, Daisy is a beloved companion. She enjoys hopping around, relaxing in comfortable spaces, and receiving gentle attention. Daisy's diet includes a mix of fresh hay, vegetables, and specially formulated rabbit pellets."
    },
    {
      id: 97,
      type: "rabbit",
      name: "Buster",
      age: 1,
      gender: "male",
      weight: "1.0 lbs",
      breed: "Mini Satin",
      alt: "Shiny Mini Satin rabbit",
      image: "/rabbits/Mini-Satin.jpg",
      description: "Introducing Buster, the sleek Mini Satin rabbit. With his shiny coat and playful disposition, Buster is a delightful pet. He enjoys hopping and exploring his environment, engaging in interactive play, and having plenty of toys to keep him entertained. Buster's diet consists of fresh hay, leafy greens, and high-quality rabbit pellets."
    },
    {
      id: 98,
      type: "rabbit",
      name: "Willow",
      age: 2,
      gender: "female",
      weight: "1.7 lbs",
      breed: "Rex Mix",
      alt: "Curious Rex Mix rabbit",
      image: "/rabbits/Rex-Mix.jpg",
      description: "Say hello to Willow, the charming Rex mix rabbit. With her velvety fur and playful personality, Willow is a joy to be around. She enjoys hopping around, participating in interactive play, and exploring her surroundings. Willow's diet includes a mix of fresh hay, vegetables, and high-quality rabbit pellets."
    },
    {
      id: 99,
      type: "rabbit",
      name: "Jasper",
      age: 3,
      gender: "male",
      weight: "2.0 lbs",
      breed: "Chinchilla",
      alt: "Fluffy Chinchilla rabbit",
      image: "/rabbits/Chinchilla.jpg",
      description: "Meet Jasper, the beautiful Chinchilla rabbit. With his soft, dense fur and curious nature, Jasper is a captivating companion. He enjoys hopping around, having plenty of toys to play with, and receiving gentle attention. Jasper's diet consists of fresh hay, a variety of vegetables, and high-fiber rabbit pellets."
    }
  ]);
};